FROM node:22-bookworm-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @hotel/api build

FROM base AS runner
WORKDIR /app
# Giữ lại toàn bộ code đã build để dễ dàng chạy các script như typeorm migration
COPY --from=builder /app /app
WORKDIR /app/apps/api

EXPOSE 3000
CMD pnpm run migrate:run && node dist/main.js
